/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_gaidamaka_jni_CPUInfo */

#ifndef _Included_ru_gaidamaka_jni_CPUInfo
#define _Included_ru_gaidamaka_jni_CPUInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_gaidamaka_jni_CPUInfo
 * Method:    getInfo
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_ru_gaidamaka_jni_CPUInfo_getInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
